language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t makkii/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true makkii/docker-react npm run test -- --coverage
